blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'  # app namespace

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('posts/', views.post_list, name='post_list'),
    # class-based post list view:
    # path('posts/', views.PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>',
         views.post_detail,
         name='post_detail'),
    path('<int:post_id>/share/',
         views.post_share, name='post_share'),
    path('<int:post_id>/comment/',
         views.post_comment, name='post_comment'),
    path('search/', views.post_search, name='post_search'),
]

mysite/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

# maps section names to sitemap classes
sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class Post(models.Model):

    class Status(models.TextChoices):  # enum class
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    thumbnail = models.ImageField(upload_to='blog/static/images/thumbnails/',
                                  default='blog/static/images/thumbnails/post_default_thumbnail.png')
    # TODO: debug publish date timezone/url issue
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)
    tags = TaggableManager()

    class Meta:
        # sort query results by publish date
        ordering = ['-publish']
        # index query results on publish date for efficient retrieval
        indexes = [models.Index(fields=['-publish']), ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """Returns the absolute URL of the post detail view for this post."""

        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])


class Comment(models.Model):

    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=100)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # for manually deactivating comments using the admin site
    active = models.BooleanField(default=True)

    class Meta:
        # sort query results by created date
        ordering = ['created']
        # index query results on created date for efficient retrieval
        indexes = [
            models.Index(fields=['created'])
        ]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=50, label="Your name")
    email = forms.EmailField(label="Your email address")
    to = forms.EmailField(label="Recipient's email address")
    comments = forms.CharField(label="Add a message",
                               required=False,
                               widget=forms.Textarea(attrs={'rows': 5}))


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'body']
        labels = {'name': 'Your name', 'body': 'Comment'}


class SearchForm(forms.Form):
    query = forms.CharField(
        label=False,
    )

blog/views.py
from .models import Post
from .forms import EmailPostForm, CommentForm, SearchForm
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count


def homepage(request):
    """
    Blog homepage view.
    """

    return render(request, 'blog/index.html')


def post_list(request, tag_slug=None):
    """
    Post list view.

    Renders a template displaying all published posts in paginated form.
    Optionally filters posts by provided tag slug URL parameter.

    Parameters:
        - (optional) `tag_slug`: The slug identifier of the tag to filter by.

    Context variables:
        - `posts`: A Page object containing a list of Post objects.
        - `tag`: A Tag object if slug is provided, or None.
    """

    post_list = Post.objects.filter(status='PB')
    tag = None

    # If tag_slug provided, filter posts by tag
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])

    # Paginate posts - 3 posts per page
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        # If page not an integer, show first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page number out of range, show last page
        posts = paginator.page(paginator.num_pages)

    return render(request,
                  'blog/post/list.html',
                  {'posts': posts, 'tag': tag})


def post_detail(request, year, month, day, post):
    """
    Post detail view.

    Renders a template displaying a single published post,
    along with comments, a form for posting new comments,
    and a list of recommended posts.

    Parameters:
        - `year`: The year of the post's publication.
        - `month`: The month of the post's publication.
        - `day`: The day of the post's publication.
        - `post`: The unique slug identifier of the post.

    Context variables:
       - `post`: The Post object representing the displayed post.
       - `comments`: A QuerySet of active comment objects related to the post.
       - `form`: An instance of the CommentForm for posting new comments.
       - `similar_posts`: A QuerySet of recommended Posts sharing common tags with the post.
    """

    post = get_object_or_404(Post,
                             status=Post.Status.PUBLISHED,
                             slug=post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    # Active comments for this post
    comments = post.comments.filter(active=True)

    # New comment form
    comment_form = CommentForm()

    # List of similar, recommended posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.objects.filter(status='PB')\
                                .filter(tags__in=post_tags_ids)\
                                .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                 .order_by('-same_tags', '-publish')[:4]

    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})


class PostListView(ListView):
    """Alternative class-based post list view."""

    # Set queryset attribute to filter posts to display
    queryset = Post.objects.filter(status='PB')

    # Set context_object_name attribute to be referenced in template
    context_object_name = 'posts'

    # Enable pagination - 3 posts per page
    paginate_by = 3

    # Specify template to render the view
    template_name = 'blog/post/list.html'


def post_share(request, post_id):
    """
    Shares a published post by email using a form.

    Displays a form for entering sender and recipient details,
    Sends an email recommendation with a link to the specified post.

    Parameters:
        - `post_id`: The ID of the post to share.

    Context variables:
        - `post`: The Post object to be shared.
        - `form`: An instance of EmailPostForm.
        - `sent`: A boolean indicating whether the email was successfully sent.
    """

    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url())
            subject = f"{data['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}" \
                      f"{data['name']}\'s comments: {data['comments']}"
            send_mail(subject, message,
                      'kester.violet.j@gmail.com', [data['to']])
            sent = True

    else:
        form = EmailPostForm()

    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})


@require_POST
def post_comment(request, post_id):
    """
    Create and save a comment for a published post.

    Parameters:
        - `post_id`: The ID of the post for which the comment is being created.

    Context variables:
        - `post`: The Post object for which the comment is created.
        - `comment_form`: An instance of the CommentForm for entering new comments.
        - `comment`: The newly created Comment object, or None if no comment was created.
    """

    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    comment_form = CommentForm()

    # instantiate form using submitted POST data when a comment is posted
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # create a comment without saving it to the database
        comment = form.save(commit=False)
        # assign comment to post
        comment.post = post
        # save the comment to the database
        comment.save()

    return render(request, 'blog/post/comment.html',
                  {'post': post,
                   'comment_form': comment_form,
                   'comment': comment})


def post_search(request):
    """
    Renders a template of blog posts matching a query.

    Context variables:
        - `query` - The query string entered by the user.
        - `results` - A QuerySet of Post objects that match the query by title
                      or body, ordered by relevance.
    """

    query = None
    results = []

    # Check if 'query' string is in POST data
    if 'query' in request.POST:
        # Create a SearchForm instance using POST data
        form = SearchForm(request.POST)
        # Validate form using rules defined in SearchForm class
        if form.is_valid():
            # Get cleaned query data from the form
            # The cleaned_data dictionary contains the validated form data
            query = form.cleaned_data['query']
            # Create a search vector based on title and body fields of posts
            search_vector = SearchVector('title', 'body')
            # Use the search vector and query to filter posts by status,
            # annotate posts with a search rank based on relevance,
            # and order posts by descending rank value
            results = Post.objects.filter(status='PB').annotate(
                search=search_vector,
                rank=SearchRank(search_vector, query)
            ).filter(search=query).order_by('-rank')

    return render(request,
                  'blog/post/search.html',
                  {'query': query,
                   'results': results})

blog/templates/blog/base.html
{% load blog_tags %}

{% load static %}

<!DOCTYPE html>
<html>

<head>
  <title>{% block title %}{% endblock %}</title>

  <!-- Bootstrap theme -->
  <link href="{% static 'css/blog-theme-bootstrap.min.css' %}" rel="stylesheet">
  <!-- Bootstrap icons -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
  <!-- Google fonts -->
  <link href="https://fonts.googleapis.com/css2?family=Homemade+Apple&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap"
    rel="stylesheet">
  <!-- Custom stylesheet -->
  <link href="{% static 'css/styles.css' %}" rel="stylesheet">
  <!-- Favicon -->
  <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
  <!-- Htmx -->
  <script src="https://unpkg.com/htmx.org@1.9.8"
    integrity="sha384-rgjA7mptc2ETQqXoYC3/zJvkU7K/aP44Y+z7xQuJiVnB/422P/Ak+F/AqFR7E4Wr"
    crossorigin="anonymous"></script>
  <!-- Htmx - enable view transitions -->
  <meta name="htmx-config" content='{"globalViewTransitions":true}'>
  <!-- Hyperscript -->
  <script src="https://unpkg.com/hyperscript.org@0.9.12"></script>
</head>

<body hx-boost="true">
  <div class="container-fluid">

    <!-- Navbar -------------------------------->
    {% include './navbar.html' %}

    <!-- Sidebar ------------------------------->
    {% include './sidebar.html' %}

    <!-- Content ------------------------------->
    <main class="p-5 mt-5 mx-5">
      <div id="content" class="container col-12 col-lg-7 col-xl-6 px-0 py-5 px-md-5">
        {% block content %}
        {% endblock %}
      </div>
    </main>

  </div>
  <!-- Bootstrap -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
</body>

</html>

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block title %}Blog Title - Home{% endblock %}

{% block content %}
<p class="text-center">This is the homepage.</p>
{% endblock %}

blog/templates/blog/navbar.html
{% load static %}

<nav class="navbar navbar-dark glassy fixed-top p-3">
  <div class="container-fluid justify-content-between">

    <!-- Logo -->
    <a class="navbar-brand" href="{% url 'blog:homepage' %}">
      <img src="{% static 'images/logo_square_300px.png' %}" alt="Logo" height="35px">
    </a>

    <div class="d-flex col-6 col-md-5 col-lg-4 col-xl-3 justify-content-end px-0">

      <!-- Search form -->
      <div id="searchFormContainer" class="fade-out col-12 px-0">
        {% include './post/forms/search_form.html' %}
      </div>

      <!-- Toggle search form -->
      <button
        class="btn btn-outline-primary ml-2"
        aria-label="Toggle search form"
        _="on click toggle between .fade-in and .fade-out on #searchFormContainer">
          <i class="bi-search"></i>
      </button>

      <!-- Toggle sidebar -->
      <button
        class="btn btn-outline-primary ml-2"
        aria-label="Toggle sidebar"
        _="on click toggle between .slide-down and .slide-up on #sidebar">
          <i class="bi-x-lg"></i>
      </button>


    </div>

  </div>
</nav>

blog/templates/blog/sidebar.html
{% load blog_tags %}

<aside id="sidebar" class="glassy slide-up col-12 col-lg-3 mt-5 p-5 pr-lg-3 pr-xl-5 position-fixed top-0 border border-secondary">
  <div class="container col-10 col-sm-6 col-lg-12 py-5 text-center text-lg-right">

    <!-- Header -->
    <header class="mb-5">
      <h1>
        <a href="{% url 'blog:homepage' %}">blog</a>
      </h1>
      <h5>blog / subtitle / here</h5>
    </header>

    <!-- Description -->
    <div class="mb-5 pt-2">
      <p>Blog description.</p>
      <p>
        Nulla facilisi. Aliquam erat volutpat. Vivamus dapibus eros vel urna.
        Sed viverra tellus in hac habitasse platea dictumst vestibulum.
      </p>
      <p>Brief bio.</p>
      <!-- <p>I've written {% total_posts %} posts so far.</p> -->
    </div>

    <!-- Latest posts -->
    <div class="mb-5 pt-4">
      <h3>Latest posts</h3>
      {% show_latest_posts 3 %}
    </div>

    <!-- Most commented posts -->
    <div class="mb-2 pt-4">
      <h3>Most commented</h3>
      {% get_most_commented_posts as most_commented_posts %}
      <ul class="mt-4">
        {% for post in most_commented_posts %}
        <li class="mt-2">
          <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
        {% endfor %}
      </ul>
    </div>

  </div>
</aside>